// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjdNzuhybE9p1CVKMPf4q6bIG2g6Bq37E',
    appId: '1:293006696968:android:00244997e599a6f615e7bd',
    messagingSenderId: '293006696968',
    projectId: 'lc-mynotes',
    storageBucket: 'lc-mynotes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAs31S1Mvo-BZN5qd5z1N4PuZGKV-qD2Jk',
    appId: '1:293006696968:ios:7bcdaadd9eda7f9415e7bd',
    messagingSenderId: '293006696968',
    projectId: 'lc-mynotes',
    storageBucket: 'lc-mynotes.appspot.com',
    iosClientId: '293006696968-rgk6brpku4k487ah36apuknrqrp7jvul.apps.googleusercontent.com',
    iosBundleId: 'dev.lonniecoffman.mynotes',
  );
}
